### ISSUE TITLE
Cambio de tema

### ISSUE THREAD

**Issue by ThaisArm** [Keybrish/ProyectoAppBusesPasajero#8]
Se solicita un cambio en la temática de la aplicación (color) ya que esta configurada con el tema por defecto de Android Studio cuando debería ir de acuerdo al branding de la aplicación.

**Comment by Keybrish** [comment]
Ya realicé el cambio, necesito la aprobación para mandar a develop
![image](https://github.com/Keybrish/ProyectoAppBusesPasajero/assets/93953328/f5312f14-c5f3-4108-a617-c1fa17f89bf8)

**Comment by ThaisArm** [comment]
Gracias por efectuar el cambio, se puede proceder a hacer la fusión de cambios con develop
